name: Metaplanet Daily Short Position Agg

on:
  schedule:
    - cron: '30 8 * * 1-5' # Runs every mon-fri at 1:30 AM PDT
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install papermill pandas kaggle beautifulsoup4 xlrd matplotlib ipykernel

      - name: Create .kaggle directory
        run: mkdir -p ~/.kaggle

      - name: Write kaggle.json
        run: |
          echo "{\"username\":\"${KAGGLE_USERNAME}\",\"key\":\"${KAGGLE_KEY}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

      - name: Run daily JPX scraper pyscript
        run: |
          papermill shorts/daily_jpx_crawler.ipynb shorts/output_daily_jpx_crawler.ipynb
